config/routes.rb
WunderStore::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' } do
    get '/signup' => 'devise/registrations#new', as: 'sign_up'
    get '/login' => 'devise/sessions#new', as: 'login'
    delete '/logout' => 'devise/sessions#destroy', as: 'logout'
  end

  root :to => 'pages#home'

  resources :products
  resources :orders, only: [:create, :edit, :index, :show] do
    get 'checkout', :on => :member
    get 'confirm', :on => :member
    post 'complete', :on => :member
    
    resources :payments do
      get :transfer, :on => :member
    end
  end
  resources :payments do
    resources :transfers
  end
  resources :transfers
  
  authenticate :user do
    mount Resque::Server => "/resque"
  end
  
  match ':action' => 'pages'
  

end

app/models/order.rb
class Order
  include Mongoid::Document
  
  field :email, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :token, type: String
  
  belongs_to :user

  embeds_one :address
  has_many :line_items, autosave: true
  has_many :payments, dependent: :destroy
  
  def total
    line_items.map(&:total).sum
  end
  
  def add_variant(variant, quantity=1)
    current_item = find_line_item_by_variant(variant)
    if current_item
      current_item.quantity += quantity
      current_item.save
    else
      current_item = LineItem.new(quantity: quantity)
      current_item.variant = variant
      current_item.price = variant.price
      self.line_items << current_item
    end
    current_item
  end
  
  def find_line_item_by_variant(variant)
    line_items.detect { |line_item| line_item.variant_id == variant.id }
  end
  
  def fill_with_paypal_details(token)
    self.token = token
    paypal_details = PAYPAL_EXPRESS_GATEWAY.details_for(token)
    self.first_name = paypal_details.params['first_name']
    self.last_name = paypal_details.params['last_name']
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders.all
  end
  
  def create
    @order = Order.new(params[:order])
    
    params[:variants].each do |variant_id, quantity|
      variant = Variant.find(variant_id)
      quantity = quantity.to_i
      @order.add_variant(variant, quantity) if quantity > 0
    end if params[:variants]
    
    @order.save
    redirect_to edit_order_path(@order)
  end
  
  def show
    @order = current_user.orders.find(params[:id])
  end
  
  def edit
    @order = Order.find(params[:id])
  end
  
  def checkout
    @order = Order.find(params[:id])
    # render text: options(@order)
    options = paypal_options(@order)
    response = PAYPAL_EXPRESS_GATEWAY.setup_purchase(options[:money], options)
    
    unless response.success?
      paypal_error(response)
      redirect_to edit_order_url(@order)
      return
    end
    
    redirect_to PAYPAL_EXPRESS_GATEWAY.redirect_url_for(response.token)
  end
  
  def confirm
    @order = Order.find(params[:id])
    options = {token: params[:token], payer_id: params[:PayerID]}
    
    paypal_details = PAYPAL_EXPRESS_GATEWAY.details_for(params[:token])
    if paypal_details.success?
      @order.token = params[:token]
      @order.first_name = paypal_details.params['first_name']
      @order.last_name = paypal_details.params['last_name']
      @order.email = paypal_details.params['payer']
      # @order.payer_id = paypal_details.params['payer_id']
      # @order.payer_country = paypal_details.params['payer_country']
      # @order.payer_status = paypal_details.params['payer_status']
      @order.save
      
      render 'confirm'
    else
      paypal_error(paypal_details)
      redirect_to edit_order_url(@order)
    end
  end
  
  def complete
    @order = Order.find(params[:id])
    options = {token: params[:token], payer_id: params[:PayerID]}
    
    response = PAYPAL_EXPRESS_GATEWAY.purchase((@order.total * 100).to_i, options)

    if response.success?
      payment = @order.payments.create(amount: response.params['gross_amount'])
      payment.complete!
      # redirect_to order_path(@order)
    else
      paypal_error(response)
      redirect_to edit_order_url(@order)
    end
  end
  
  private
  def paypal_options(order)
    items = order.line_items.map do |line_item|
      description = (line_item.variant.product.description or '')[0..120]
      price = (line_item.price * 100).to_i # price in cents
      { name: line_item.variant.product.name,
        description: description,
        quantity: line_item.quantity,
        amount: price }
    end
    
    opts = {
      return_url: confirm_order_url(order),
      cancel_return_url: edit_order_url(order),
      order_id: order.id.to_s,
      custom: order.id.to_s,
      items: items,
      money: (order.total * 100).to_i
    }
    opts
  end
  
  def paypal_error(response)
    error = response.params[:message] ||
            response.params[:response_reason_text] ||
            response.message
    error_message = "#{I18n.t('gateway_error')} ... #{error}"
    logger.error(error_message)          
    flash[:alert] = error_message
  end
end

app/views/orders/_address_fields.html.erb
<p>
  <%= f.label :address %>
  <%= f.text_field :address %>
</p>
<p>
  <%= f.label :city %>
  <%= f.text_field :city %>
</p>
<p>
  <%= f.label :state %>
  <%= f.text_field :state %>
</p>
<p>
  <%= f.label :zipcode %>
  <%= f.text_field :zipcode %>
</p>
<p>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
</p>
<p>
  <%= f.label :country %>
  <%= f.select(:country, [['Brazil', 1]]) %>
</p>

app/views/orders/_form.html.erb
<%
=begin
%>
<%= form_for :order do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>  
  <%= f.fields_for :address do |address_builder| %>
    <%= render 'address_fields', f: address_builder %>
  <% end %>
  
  <% # = f.submit 'Checkout', type: :image, src: 'https://www.paypalobjects.com/en_US/i/btn/btn_xpressCheckout.gif' %>
<% end %>
<%
=end
%>
<%= link_to image_tag('https://www.paypalobjects.com/en_US/i/btn/btn_xpressCheckout.gif'), checkout_order_path(@order), :id => 'Checkout' %>

app/views/orders/complete.html.erb
<h1>Order completed</h1>
<br/>
<p>
  <label>Total</label>
  <strong class="total"><%= @order.total %></strong>
</p>
<p>
  <label>First Name</label>
  <strong class="first-name"><%= @order.first_name %></strong>
</p>
<p>
  <label>Last Name</label>
  <strong class="last-name"><%= @order.last_name %></strong>
</p>

app/views/orders/confirm.html.erb
<h1><%= t("confirm") %></h1>
<p>
  <%= raw t("order_not_yet_placed") %>
</p>

<div>
  <%= button_to 'Place Order', complete_order_url(@order, {:token => params[:token] , :PayerID => params[:PayerID]} ) %>
</div>

app/views/orders/edit.html.erb
<p>Total: R$ <strong class="order-price"><%= @order.total %></strong></p>

<%= render 'form' %>

app/views/orders/index.html.erb
<ul>
  <% @orders.each do |order| %>
  <li><%= link_to order.id.to_s, order_path(order) %></li>
  <% end %>
</ul>

app/views/orders/show.html.erb
<p>
  <label>#ID</label>
  <strong class="id"><%= @order.id %></strong>
</p>
<p>
  <label>Total</label>
  <strong class="total"><%= @order.total %></strong>
</p>
<p>
  <label>First Name</label>
  <strong class="first-name"><%= @order.first_name %></strong>
</p>
<p>
  <label>Last Name</label>
  <strong class="last-name"><%= @order.last_name %></strong>
</p>
<%= link_to 'Payments', order_payments_path(@order) %>