config/routes.rb
WunderStore::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' } do
    get '/signup' => 'devise/registrations#new', as: 'sign_up'
    get '/login' => 'devise/sessions#new', as: 'login'
    delete '/logout' => 'devise/sessions#destroy', as: 'logout'
  end

  root :to => 'pages#home'

  resources :products
  resources :orders, only: [:create, :edit, :index, :show] do
    get 'checkout', :on => :member
    get 'confirm', :on => :member
    post 'complete', :on => :member
    
    resources :payments do
      get :transfer, :on => :member
    end
  end
  resources :payments do
    resources :transfers
  end
  resources :transfers
  
  authenticate :user do
    mount Resque::Server => "/resque"
  end
  
  match ':action' => 'pages'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WunderStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/application.widget.erb
<!DOCTYPE html>
<html>
<head>
  <title>WunderStore</title>
  <%= stylesheet_link_tag    "widget", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <div class="container">
    <%= yield %>
  </div>
  
  <div class="widget theme-<%= @product.theme %>">
    widget
  </div>

</body>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WunderStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <ul>
    <li><%= link_to t('home'), root_url %></li>
    <li><%= link_to t('about'), '/about' %></li>
    <li><%= link_to t('sign_up'), sign_up_url %></li>
    <li><%= link_to t('facebook_connect'), user_omniauth_authorize_path(:facebook) %></li>
    <li><%= link_to t('login'), login_url %></li>
  </ul>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>